sudo: required
language: Cpp
os:
  - linux
  # - osx
compiler:
  - clang
  - gcc

install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh)
  # - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
    # - gcc-4.8
    # - g++-4.8
    # - clang
    - valgrind
    - lcov

before_script:
  - sh ./install_cpputest.sh
script:
  - xmake f -m coverage
  - xmake
  - ls && ls build
  - ls /usr/lib/ccache
  - ls $HOME/.ccache
  - echo $PATH
  - find . -name "run_all_tests"
  - ./build/run_all_tests
  - valgrind -v --suppressions=./valgrind.suppressions --run-libc-freeres=no --error-exitcode=42 build/run_all_tests

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory build/.objs/run_all_tests/source/predem/ --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
